### ISSUE TITLE
Search a codelist on the code/name/description fields

### ISSUE THREAD

**Issue by andylolz** [codeforIATI/codelists#12]
On codelist pages, I’d like a typeahead search, so that I can quickly find the name of a given code and vice versa.

**Comment by andylolz** [comment]
I had a go at this (by adding `h2`s throughout the codelist tables) but it didn’t get picked up by vuepress search :( so I’m not sure the best way to solve.

**Comment by matmaxgeds** [comment]
Maybe this might help if we can add tags - 18 days old? https://github.com/vuejs/vuepress/pull/1557##

Or slightly more involved but supported/integrated: https://vuepress.vuejs.org/theme/default-theme-config.html#algolia-docsearch

**Comment by andylolz** [comment]
> Or slightly more involved but supported/integrated: https://vuepress.vuejs.org/theme/default-theme-config.html#algolia-docsearch

Oh… I assumed this was a paid-for service, but it appears to be free!

**Comment by andylolz** [comment]
> Maybe this might help if we can add tags - 18 days old? vuejs/vuepress#1557

Interesting! Looks like this is in v1.4.0.

**Comment by markbrough** [comment]
I think Algolia DocSearch looks quite nice and would be easy to implement quickly! Should we (I?) have a go at this?

**Comment by andylolz** [comment]
Sure – go for it!

**Comment by andylolz** [comment]
This would be increasingly useful now that some codelists are paginated, since ctrl-F won't search the whole of a paginated codelist.

**Comment by stevieflow** [comment]
To add: as a user, I try to use the global search to search a codelist, and get confused by the results (or lack of)

**Comment by markbrough** [comment]
Added the option to filter on a particular codelist page in #71

**Comment by andylolz** [comment]
I reckon #71 closes this.
