### ISSUE TITLE
Links to category codelists are broken

### ISSUE THREAD

**Issue by andylolz** [codeforIATI/codelists#19]
This bit here:
https://github.com/codeforIATI/codelists/blob/706492278b51b5098974ed4437d5edb95e1c32d3/static/.vuepress/components/CodelistPage.vue#L14

For example, the [AidType codelist](https://codelists.codeforiati.org/AidType/) description links to:
https://codelists.codeforiati.org/AidType/AidType-category

**Comment by andylolz** [comment]
I’ve assigned to you, @markbrough, because I don’t know what the Vue.js way to fix this is.

**Comment by markbrough** [comment]
Fixed in #25
