### ISSUE TITLE
Show when a codelist was last updated

### ISSUE THREAD

**Issue by markbrough** [codeforIATI/codelists#55]
Make it possible to see on the website when a particular codelist was last updated.

Also: show when the site as a whole was last generated?

**Comment by andylolz** [comment]
Nice!

I quite like the idea of a "last checked for updates" date, too. That’s because: A "last updated" date of 6 months ago doesn’t necessarily mean the data is out of date. It’s possible that the source is stable, so hasn’t been updated for a while.

**Comment by markbrough** [comment]
> EDIT: Oh… Possible this is exactly what you mean by the "last generated" date?

That wasn't what I meant but I think it's a good idea -- I guess we have three types of updated dates:
1. last change to a codelist;
2. last time we confirmed a codelist is consistent with the source;
3. last time the site itself was built.

I agree the "last checked for updates" idea is good!
